### ISSUE TITLE
Can't display a SunBurst, Doughnut displays correctly with  the same data

### ISSUE THREAD

**Issue by StroomWorks21** [stroomworks/stroom-visualisations-dev#8]
![image](https://github.com/user-attachments/assets/a47e0f93-4a72-46f0-b081-f6e23a3c8d68)

![image](https://github.com/user-attachments/assets/a7b2aabb-8d36-428e-88c1-f11cfebc4048)

**Comment by stroomworks3401** [comment]
sunburst uses hierarchical data with a delimiter between values. I don't think doughnut does.

example sunburst data:

data = [
                ["flare/analytics/cluster/AgglomerativeCluster", 3938],
                ["flare/analytics/cluster/CommunityStructure", 3812],
                ["flare/analytics/cluster/HierarchicalCluster", 6714],
                ["flare/analytics/cluster/MergeEdge", 743],
                ["flare/analytics/graph/BetweennessCentrality", 3534],
                ["flare/analytics/graph/LinkDistance", 5731],
                ["flare/analytics/graph/MaxFlowMinCut", 7840]
               ]

**Comment by stroomworks3401** [comment]
sunburst should work in stroom and test env now
